### ISSUE TITLE
Cloudformation Template no longer works

### ISSUE THREAD

**Issue by RafalLukawiecki** [simalexan/sns-lambda-subscriber-dynamodb#2]
It uses an unsupported Node version. Message:

The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;

**Comment by simalexan** [comment]
Hi @RafalLukawiecki ill be checking this one in a few hours. It will be updated

**Comment by simalexan** [comment]
@RafalLukawiecki this has been updated and published. Feel free to try out and ping if you encounter issues!

**Comment by RafalLukawiecki** [comment]
Thank you!
